### PR TITLE
CBA deployment prep

### PR DESCRIPTION
**Pull request by chuckwondo**
Modify deployment to allow for deployment to both our "old" AWS accounts as well as our "new" CBA accounts.

@krisstanton and @jsrikish, before approving this PR, I want you both to be able to successfully deploy to the CBA sandbox account, as follows:

First, fetch the code:

```
git fetch
git checkout cba-deployment-prep
git pull
```

Next, update your `.env` file as follows:

- Comment out your current values for `AWS_PROFILE`, `TS_ENV`, and `TF_VAR_cumulus_distribution_uri`
- Add new lines for each of those same 3 variables:
  - Set `AWS_PROFILE` to the profile you created for the CBA sandbox (perhaps `csda-cumulus-sbx-7894`)
  - Set `TS_ENV` to something slightly different, perhaps the same as the `TS_ENV` you just commented out, but with `cba` as the suffix.
  - Initially comment out `TF_VAR_cumulus_distribution_url=` without a value (you won't know the value until after the first deployment)

Next, setup and deploy everything. You will eventually (after 30-60 minutes?) be prompted to supply your username and password for your account at https://uat.urs.earthdata.nasa.gov/:

```
make pre-deploy-setup
make all-up-yes
```

You may have to run `make all-up-yes` 2 or 3 times for a clean deploy.

Once you get a clean deploy, you have to set `TF_VAR_cumulus_distribution_url` as follows:

- Run `make output-cumulus`
- Find value of `cumulus_distribution_api_uri` and set that as the value of `TF_VAR_cumulus_distribution_url` in your `.env` file (and uncomment the line)
- Run `make all-up-yes` one last time (hopefully)

### CODE REVIEW

**Comment by jsrikish** [comment]
Changed the .env file with TS_ENV=jayanthi-sbx
make pre-deploy-setup
bundler: failed to load command: terraspace (/opt/terraspace/embedded/bin/terraspace)
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.168.4/lib/aws-sdk-core/param_validator.rb:35:in `validate!': missing required parameter params[:role_arn] (ArgumentError)
................................
................................
ERROR: No S3 bucket specified

Usage: bin/copy-launchpad-pfx.sh BUCKET

**Comment by chuckwondo** [comment]
Did you also set `AWS_PROFILE` (in `.env`) to the CBA sandbox profile you created?

Once you make sure `AWS_PROFILE` is set correctly, completely rebuild the Docker image:

```
docker builder prune -af
make docker
```

Then try again:

```
make pre-deploy-setup
```

**Comment by krisstanton** [comment]
I got my sandbox deploy all the way to the smoke test stage and found an error that I think requires a code change.
The Error '`NoSuchBucket`' (and MANY similar errors) happens when trying to upload granule samples to this location.
`s3://csdap-cumulus-kris-sbx7894-provider/storage-ss-ingest-prod-ingesteddata-uswest2/planet/PSScene3Band-20171201_031958_0f31/20171201_031958_0f31_thumb`	

I looked in S3 and found that the below bucket exists
`s3://csda-cumulus-kris-sbx7894-provider-7894`
The bucket that the smoke test is looking for to upload is
`s3://csdap-cumulus-kris-sbx7894-provider`
Just to note, my .env file has a line that looks like this
`TS_ENV=kris-sbx7894`

To fix this,
Somewhere in the the smoke test code needs to:
Need to remove a 'p' (character position 4) and need to add '-7894' to the end of the bucket name.

I looked a little bit deeper and found the parts of the code which set this.
Makefile --> (create-test-data) ---> bin/create-test-data.sh

Fixing the code
The exact code that sets this is in the file:
`bin/create-test-data.sh`

Line: 11:	`_bucket_prefix=$(test "${TS_ENV}" == "uat" && echo "csdap-uat-" || echo "csdap-${CUMULUS_PREFIX}-")
`
If my .env file is: 
`TS_ENV=kris-sbx7894`
This state of line 11 sets _bucket_prefix to
`csdap-cumulus-kris-sbx7894-`
When it should set it to
`csda-cumulus-kris-sbx7894-`

Line: 14 	`_provider_bucket=${_bucket_prefix}provider`
From the above example '_provider_bucket' gets set to
`csdap-cumulus-kris-sbx7894-provider`
When it should be set to
`csda-cumulus-kris-sbx7894-provider-7894`

**Comment by chuckwondo** [comment]
@krisstanton, this ticket is for _deployment_ only, not for dealing with test data.

I'm working on a separate branch for us to deal with test data, which addresses the issue you pointed out, among many other things that we also need.

Approve this PR if your deployment succeeded. Skip creating test data at this point.

**Comment by krisstanton** [comment]
Sorry, I was under the impression that we had to get a smoke test pass before it counted as a complete deploy.
Understood about separate branch for the smoke test issue.  Thanks for the clarity.

The only other thing I should mention before clicking approve is that when I run
`make output-cumulus`
I get a blank space for cumulus_distribution_api_uri (see below).
However, when I go to AWS API Gateway, the distribution API is present and has an address.

`
➜  csdap-cumulus git:(cba-deployment-prep) ✗ make output-cumulus
sha256:<LONG_STRING_HERE>
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Building .terraspace-cache/us-west-2/kris-sbx7894/stacks/cumulus
Current directory: .terraspace-cache/us-west-2/kris-sbx7894/stacks/cumulus
=> terraform output
archive_api_redirect_uri = https://t9maohtgsi.execute-api.us-west-2.amazonaws.com:8000/dev/token
archive_api_uri = https://t9maohtgsi.execute-api.us-west-2.amazonaws.com:8000/dev/
cumulus_distribution_api_redirect_uri = login
cumulus_distribution_api_uri = 
report_executions_sns_topic_arn = arn:aws:sns:us-west-2:772632177894:cumulus-kris-sbx7894-report-executions-topic
report_granules_sns_topic_arn = arn:aws:sns:us-west-2:772632177894:cumulus-kris-sbx7894-report-granules-topic
report_pdrs_sns_topic_arn = arn:aws:sns:us-west-2:772632177894:cumulus-kris-sbx7894-report-pdrs-topic
stepfunction_event_reporter_queue_url = https://sqs.us-west-2.amazonaws.com/772632177894/cumulus-kris-sbx7894-sfEventSqsToDbRecordsInputQueue
`

So I can just manually grab the URI, which for my deploy is:  https://gc86mo52vh.execute-api.us-west-2.amazonaws.com/dev/

Sorry if this issue is also out of scope.  Let me know if so and I'll click approve.

Thanks!

**Comment by chuckwondo** [comment]
@krisstanton, if you did your initial deployment with the following line in your `.env` file, then perhaps that's why the uri in the outputs has no value:

```
TF_VAR_cumulus_distribution_url=
```

Perhaps you didn't have that line commented out on the first deploy?

**Comment by krisstanton** [comment]
> Perhaps you didn't have that line commented out on the first deploy?

You are absolutely right.  I had not commented that line out.  That makes sense.  Ok going to click approve now.
Thanks!

**Review by krisstanton — APPROVED** [review]

**Comment by chuckwondo** [comment]
@jsrikish, if you're still having a problem with this, let's do the following:

1. Paste the contents of your `.env` file in a reply to this comment
2. Run `git log -1 --oneline` and paste the output in a reply

If I cannot discern the issue from this information, then let's setup a meeting to debug things.

**Comment by jsrikish** [comment]
> Did you also set `AWS_PROFILE` (in `.env`) to the CBA sandbox profile you created?
> 
> Once you make sure `AWS_PROFILE` is set correctly, completely rebuild the Docker image:
> 
> ```
> docker builder prune -af
> make docker
> ```
> 
> Then try again:
> 
> ```
> make pre-deploy-setup
> ```

I tried the above commands but it failed in docker pre-deploy-setup with the same error

**Comment by jsrikish** [comment]
> @jsrikish, if you're still having a problem with this, let's do the following:
> 
> 1. Paste the contents of your `.env` file in a reply to this comment
> 2. Run `git log -1 --oneline` and paste the output in a reply
> 
> If I cannot discern the issue from this information, then let's setup a meeting to debug things.

`cat .env
#-------------------------------------------------------------------------------
# Environment variables that are automatically set when making any of the
# targets in the Makefile that run commands in the Docker container.
#-------------------------------------------------------------------------------

# The Terraspace "environment"
#
# ** IMPORTANT **
#
# For UAT, SIT, or Prod environments, this must be "uat", "sit", or "prod",
# respectively.
#
# For development deployments, this should be unique to you, such as your name,
# nickname, or initials (WITHOUT WHITESPACE), to distinguish your AWS resources
# from those of other Cumulus "stacks."  For example, something like "jdoe3",
# "tinytim", or something else likely to be unique to you.

TS_ENV=jayanthi-sbx7894

AWS_REGION=us-west-2

# See AWS_ACCESS_KEYS.md for details on obtaining an access key ID and secret.
# With your ID and secret you may create an AWS profile, and then set
# AWS_PROFILE (below) to the name of your newly created profile.

AWS_PROFILE=csda-cumulus-sbx-7894

# If you do not wish to create an AWS profile, set the following values
# directly (again, based on the instructions in docs/AWS_ACCESS_KEYS.md).
# NOTE: AWS_SESSION_TOKEN is used only in the case of a short-term access key.

#AWS_ACCESS_KEY_ID=
#AWS_SECRET_ACCESS_KEY=
#AWS_SESSION_TOKEN=

#-------------------------------------------------------------------------------
# Terraform variable overrides
#
# If you wish to override a Terraform variable, you may do so in this file by
# setting an environment variable with a name of the form `TF_VAR_name`, where
# `name` is the name of the Terraform variable.
#-------------------------------------------------------------------------------

# By default, the value you specify for the CMR username secret is used as the
# only username in the `api_users` Terraform variable.  If you wish to add other
# usernames, uncomment the following variable and specify the list of usernames.

# IMPORTANT: When you uncomment the next line, you must explicitly include your
# own username, as it will no longer be included implicitly.  Further, the
# format is a JSON list of strings, so the list must be enclosed by square
# brackets, and each username must be enclosed by double-quotes, and
# comma-separated from each other.

#TF_VAR_api_users=["sriki"]
TF_VAR_cumulus_distribution_url=
#TF_VAR_cumulus_distribution_url=https://mb6he58kpe.execute-api.us-west-2.amazonaws.com/dev/`

**Comment by jsrikish** [comment]
> 2\. git log -1 --oneline

` git log -1 --oneline
5dbf0ed (HEAD -> cba-deployment-prep, origin/cba-deployment-prep) Fix use of is_cba? and is_sandbox?`

**Comment by chuckwondo** [comment]
I think there's an additional command you need to run, but missed listing, so let's do this:

```
docker builder prune -af
docker system prune -f
DOCKER_BUILD_OPTS= make docker
```

I think without that 2nd "prune" command, your image was not being fully removed, so the image build was still hanging onto some old layers that might be the cause of the problem.

I think this should get your Docker container sorted out, and you should then try this again:

```
make pre-deploy-setup
```

🤞

**Comment by chuckwondo** [comment]
@jsrikish, also comment out this line in your `.env` file:

```
TF_VAR_cumulus_distribution_url=
```

Should be:

```
#TF_VAR_cumulus_distribution_url=
```

**Comment by jsrikish** [comment]
> 



> I think there's an additional command you need to run, but I missed listing it, so let's do this:
> 
> ```
> docker builder prune -af
> docker system prune -f
> DOCKER_BUILD_OPTS= make docker
> ```
> 
> I think without that 2nd "prune" command, your image was not being fully removed, so the image build was still hanging onto some old layers that might be the cause of the problem.
> 
> I think that should get your Docker container sorted out, and you should then try this again:
> 
> ```
> make pre-deploy-setup
> ```
> 
> 🤞

Didn't work :(

**Comment by chuckwondo** [comment]
OK, let's remove some docker volumes that might be causing problems:

```
docker volume list | grep -o 'csdap-cumulus[.].*' | xargs -L1 -t docker volume rm
```

Then try `make pre-deploy-setup` again.

**Comment by jsrikish** [comment]
> docker volume list | grep -o 'csdap-cumulus[.].*' | xargs -L1 -t docker volume rm

Still the same error :(

**Comment by chuckwondo** [comment]
@jsrikish, would you mind pasting into a reply the entire error output your getting?

**Pull request merged**
